name: Weddings Abroad
favicon: null
layout_spectrum: 0.9948309827595949
typography_spectrum: 0.7728624816518277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9796370626427233
  lightness: 0.7477316043805331
  saturation: 0.1419372719246894
  rhythmicContrast: 0.20062644919380546
purpose: []
